program: evaluation_pipeline.py
name: MultiEval
command:
  - python
  - -m
  - evaluation_pipeline
  - multi
method: grid
parameters:
  model_type:
    value: multi
  model_name:
    value: mediapipe
  sample_rate:
    value: 25
  dataset_path:
    value: /cluster/home/emanueal/Desktop/MoCap/segmented
  movement:
    values: [upper, lower, sitting, complex]
  augmentation:
    values: [none, defocus, underexposure, occlusion, background, desynchronize, decalibration,
             cameras_4_0, cameras_5_1, cameras_4_3, cameras_4_2, cameras_0_4_3, cameras_5_4_1, cameras_0_4_3_2]
  default_camera:
    value: [0, 4]